all: Test \
	SittingDuck  Random \
	CompactSayaka NonZeroCompactSayaka \
	Watcher \
	SayakaRevive \
	SayakaRD2 \
	KuroMadoka Kyouko KyoukoRevive KyoukoFA \
	KamijoRevive \
	KyoukoFADash \
	KyoukoFARocket \
	KyoukoSort \
	KyoukoReviveFirstAttack \
	Clone \
	Mami103 \
	FastZombie

Clone: Clone.hs LTG.hs LTG/*.hs
	ghc --make -O3 Clone.hs


CompactSayaka: CompactSayaka.hs LTG.hs LTG/*.hs
	ghc --make -O3 CompactSayaka.hs


FastZombie: FastZombie.hs LTG.hs LTG/*.hs
	ghc --make -O3 FastZombie.hs



KuroMadoka: KuroMadoka.hs LTG.hs LTG/*.hs
	ghc --make -O3 KuroMadoka.hs

Kyouko: Kyouko.hs LTG.hs LTG/*.hs
	ghc --make -O3 Kyouko.hs

KyoukoSort: KyoukoSort.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoSort.hs



KyoukoRevive: KyoukoRevive.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoRevive.hs

KamijoRevive: KyoukoRevive.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoRevive.hs -DKAMIJO

KyoukoFA: KyoukoFA.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoFA.hs

KyoukoFARocket: KyoukoFARocket.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoFARocket.hs

KyoukoFADash: KyoukoFADash.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoFADash.hs

KyoukoReviveFirstAttack: KyoukoReviveFirstAttack.hs LTG.hs LTG/*.hs
	ghc --make -O3 KyoukoReviveFirstAttack.hs

Mami103: Mami103.hs  LTG.hs LTG/*.hs
	ghc --make -O3 Mami103.hs


NonZeroCompactSayaka: NonZeroCompactSayaka.hs LTG.hs LTG/*.hs
	ghc --make -O3 NonZeroCompactSayaka.hs

Random: Random.hs  LTG.hs LTG/*.hs
	ghc --make -O3 Random.hs

SayakaRevive: SayakaRevive.hs  LTG.hs LTG/*.hs
	ghc --make -O3 SayakaRevive.hs

SayakaRD2: SayakaRD2.hs  LTG.hs LTG/*.hs
	ghc --make -O3 SayakaRD2.hs


SittingDuck: SittingDuck.hs  LTG.hs LTG/*.hs
	ghc --make -O3 SittingDuck.hs




Test: Test.hs  LTG.hs LTG/*.hs
	ghc --make -O3 Test.hs

Watcher: Watcher.hs  LTG.hs LTG/*.hs
	ghc --make -O3 Watcher.hs


